### ISSUE TITLE
Conda conflicts for notebook software environments

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/notebooks#22]
There are some conda conflicts when solving software environments for some notebooks (see https://github.com/coiled/notebooks/runs/1737519362?check_suite_focus=true for an example). @FabioRosado if you get a moment, would you mind investigating a little further?

**Comment by FabioRosado** [comment]
Sure will do

**Comment by ian-r-rose** [comment]
Temporarily fixed, but we should revisit when the software environment refactor lands
